export enum IconName {
    SEARCH = "search",
    USER = "user",
    EMAIL = "email",
    LOCK = "lock",
    CLOSE = "close",
    CHECK = "check",
    WARNING = "warning",
    INFO = "info",
    STAR = "star",
    DELETE = "delete",
    ADD = "add",
    EDIT = "edit",
    SAVE = "save",
    CHEVRON_DOWN = "chevron_down",
    CHEVRON_LEFT = "chevron_left",
    CHEVRON_RIGHT = "chevron_right",
}
