/**
 * All translation keys available in the app.
 * To add a new key, follow the pattern:
 * 1. Add the key to this enum.
 * 2. Add the key to the translation files in the respective language folder.
 * 3. Add the key to the `ResourceBase` class in `src/utils/resources/languages/resourceService.ts`.
 * 4. Add the key to the `Resource` type in `src/utils/resources/resource.ts`.
 * 5. Add the key to the `Resource` type in `src/utils/resources/resourceTypes.ts`.
 */
export const Resource = {
    ACCOUNT_NOT_FOUND: "ACCOUNT_NOT_FOUND",
    CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
    CATEGORY_NOT_FOUND_OR_INACTIVE: 'CATEGORY_NOT_FOUND_OR_INACTIVE',
    CATEGORY_OR_SUBCATEGORY_REQUIRED: 'CATEGORY_OR_SUBCATEGORY_REQUIRED',
    CONFLICT_INSTALLMENT_RECURRING: "CONFLICT_INSTALLMENT_RECURRING",
    CREDIT_CARD_NOT_FOUND: 'CREDIT_CARD_NOT_FOUND',
    EMAIL_IN_USE: "EMAIL_IN_USE",
    EMAIL_INVALID: "EMAIL_INVALID",
    EXPIRED_OR_INVALID_TOKEN: 'EXPIRED_OR_INVALID_TOKEN',
    FIRST_NAME_TOO_SHORT: "FIRST_NAME_TOO_SHORT",
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
    INVALID_ACCOUNT_ID: "INVALID_ACCOUNT_ID",
    INVALID_CATEGORY_ID: "INVALID_CATEGORY_ID",
    INVALID_CREDIT_CARD_ID: "INVALID_CREDIT_CARD_ID",
    INVALID_CRITERIA: "INVALID_CRITERIA",
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
    INVALID_CURRENCY_VALUE: 'INVALID_CURRENCY_VALUE',
    INVALID_DATE: 'INVALID_DATE',
    INVALID_DATE_FORMAT: "INVALID_DATE_FORMAT",
    INVALID_DATE_FORMAT_VALUE: 'INVALID_DATE_FORMAT_VALUE',
    INVALID_ENUM: 'INVALID_ENUM',
    INVALID_JSON: "INVALID_JSON",
    INVALID_LANGUAGE_VALUE: 'INVALID_LANGUAGE_VALUE',
    INVALID_SUBCATEGORY_ID: "INVALID_SUBCATEGORY_ID",
    INVALID_THEME_VALUE: 'INVALID_THEME_VALUE',
    INVALID_TRANSACTION_ID: "INVALID_TRANSACTION_ID",
    INVALID_TRANSACTION_TYPE: "INVALID_TRANSACTION_TYPE",
    INVALID_TYPE: 'INVALID_TYPE',
    INVALID_USER_ID: "INVALID_USER_ID",
    LAST_NAME_TOO_SHORT: "LAST_NAME_TOO_SHORT",
    LOGOUT_ATTEMPT_WITH_MISSING_TOKEN: "LOGOUT_ATTEMPT_WITH_MISSING_TOKEN",
    NO_ACCOUNTS_FOUND: "NO_ACCOUNTS_FOUND",
    NO_RECORDS_FOUND: "NO_RECORDS_FOUND",
    PASSWORD_TOO_SHORT: "PASSWORD_TOO_SHORT",
    PAYMENT_DAY_NOT_ALLOWED: "PAYMENT_DAY_NOT_ALLOWED",
    PAYMENT_DAY_OUT_OF_RANGE: "PAYMENT_DAY_OUT_OF_RANGE",
    PAYMENT_DAY_REQUIRED: "PAYMENT_DAY_REQUIRED",
    SEARCH_TERM_TOO_SHORT: "SEARCH_TERM_TOO_SHORT",
    SUBCATEGORY_NOT_FOUND: 'SUBCATEGORY_NOT_FOUND',
    SUBCATEGORY_NOT_FOUND_OR_INACTIVE: 'SUBCATEGORY_NOT_FOUND_OR_INACTIVE',
    TOKEN_NOT_FOUND: 'TOKEN_NOT_FOUND',
    TOO_BIG: 'TOO_BIG',
    TOO_SMALL: 'TOO_SMALL',
    TOTAL_MONTHS_NOT_ALLOWED: "TOTAL_MONTHS_NOT_ALLOWED",
    TOTAL_MONTHS_REQUIRED: "TOTAL_MONTHS_REQUIRED",
    TRANSACTION_NOT_FOUND: 'TRANSACTION_NOT_FOUND',
    UNAUTHORIZED_OPERATION: 'UNAUTHORIZED_OPERATION',
    UNEXPECTED_ERROR: 'UNEXPECTED_ERROR',
    UNRECOGNIZED_KEYS: 'UNRECOGNIZED_KEYS',
    USER_NOT_FOUND: "USER_NOT_FOUND",
    VALIDATION_ERROR: "VALIDATION_ERROR",
} as const;

export type Resource = keyof typeof Resource;
